### ISSUE TITLE
How do you create a datetime in tutd?

### ISSUE THREAD

**Issue by 3noch** [agentm/project-m36#104]

**Comment by agentm** [comment]
We do have a ```DateTimeAtom``` but the ```tutd``` interface is missing atom functions to construct such atoms. I'll add some default constructors to make this more useful. Sorry for the oversight!

**Comment by agentm** [comment]
I added a new ```dateTimeFromEpochSeconds``` function. Let me know if there are some other functions which would be useful. Perhaps a ```Day``` + seconds constructor?
