### ISSUE TITLE
generate and host haddock docs

### ISSUE THREAD

**Issue by agentm** [agentm/project-m36#116]
Even without comments, haddock output can be useful for navigating data types.

**Comment by 3noch** [comment]
You could release to Hackage to get this. ;)

**Comment by agentm** [comment]
Yea, I should probably just bite-the-bullet. 

Initially, I was afraid of too much "success" (in the Haskell sense) forcing me to lock down the API, but it has been rather stable for a while now. The approach of a low-level API being supplemented by a higher-level monadic API resolves my concerns.

**Comment by agentm** [comment]
I patched up the haddock docs for ProjectM36.Client and posted the package to [hackage](http://hackage.haskell.org/package/project-m36-0.1).

**Comment by 3noch** [comment]
What do you think about submitting to stackage?

**Comment by zanzix** [comment]
this is much more convenient, thanks a lot!

**Comment by agentm** [comment]
I'm not averse to submitting to stackage, but I am wary of supporting an API frozen for three months at-a-time, unless I misunderstand the purpose of the LTS releases. Other than pinning dependency versions, what are the advantages of being on stackage?

**Comment by 3noch** [comment]
The only thing you need to worry about with stackage is having dependency ranges that are wide enough to include LTS. As long as that's the case, there's really no downside.

The advantages are

  * Stackage is usually faster and more reliable at generating Haddocks
  * Nixpkgs loosely follows Stackage, so once Nixpkgs picks up a version of Stackage with Project:M36, Nix folks can install a pre-built version of it with `nix-env -i haskellPackages.project-m36`. (Note that your tests will need to pass for the pre-built part to work.)
