### ISSUE TITLE
autoMergeToHead may not be setting the new graph head

### ISSUE THREAD

**Issue by agentm** [agentm/project-m36#131]
@3noch reports that autoMergeToHead is operating differently from commit in that relvars seem to disappear instead of appearing merged in the new head transaction. I suspect that the new head is being set to an old transaction.

**Comment by agentm** [comment]
I am able to reproduce this. After running autoMergeToHead, the disconnected transaction is no longer at the head of the graph. There is something fundamentally wrong with the implementation.

**Comment by 3noch** [comment]
Hey it works! Thanks!
