### ISSUE TITLE
figure out why hlint travis script is failing

### ISSUE THREAD

**Issue by agentm** [agentm/project-m36#132]
The hlint script in .travis.yml was working for a few days, but started failing today.

```
$ curl -sL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s lint src test examples --cpp-define PROJECTM36_VERSION=HLINT
Downloading and running hlint...
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
The command "curl -sL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s lint src test examples --cpp-define PROJECTM36_VERSION=HLINT" exited with 2.
```
The "Downloading" line indicates that the package is successfully downloaded. Running the script locally appears to work, so I'm not sure what broke.

Debugging this probably requires running the script in a travis VM.

**Comment by 3noch** [comment]
Wow that's odd.

**Comment by agentm** [comment]
hlint is working again. I did not change .travis.yml nor do I see any changes in the [neil repository](https://github.com/ndmitchell/neil/commits/master/misc/travis.sh) which would account for the change. Regardless, hlint is again functioning, so I won't dig any deeper unless this happens again.

**Comment by agentm** [comment]
I am seeing this again.

**Comment by agentm** [comment]
We haven't seen this in many months.
