### ISSUE TITLE
add support for Haskell Integer type

### ISSUE THREAD

**Issue by agentm** [agentm/project-m36#138]
et4te from the IRC channel requested an "Integer" type. This could be a primitive, but I wonder if it is worth leaking the Int/Integer naming as implementation detail. Perhaps we should drop the Int64 type or specifically rename it to be "Int64" and add "Integer".

**Comment by 3noch** [comment]
@et4te

**Comment by agentm** [comment]
After discussion wtih @et4te, it might be easiest to drop "Int" support for now in preference to "Integer", both in Haskell and naming terms.

**Comment by 3noch** [comment]
@agentm Does this mean we incur the cost of full `Integer` whenever we want to use it with the database?

**Comment by agentm** [comment]
Indeed, but I suspect it would be difficult to cook up a database scenario currently whereby Integer would be a bottleneck. I think it's worth exploring, at least.

**Comment by 3noch** [comment]
Good point.

**Comment by et4te** [comment]
There is a cost in terms of space given that arbitrary sized integers are encoded differently via Binary as far as I know. Ideally all three variants are supported (Int32, Int64 and Integer / Bignum) but if you have to pick just one, Integer is the most useful in that it is a superset of the other two. In practice Int32 / Int64 is an optimisation for space or efficiency and is prone to overflow.

**Comment by agentm** [comment]
Based on IRC discussions, I have [restored](3c5ad795b5c06d7678981d76c9b977b2e4f6d19f) IntAtom alongside IntAtom with the names directly mapped to the Haskell types. Wherever possible, the Integer type is preferred, such as with the defaults in the basic AtomFunctions involving less-than, add, etc.
