### ISSUE TITLE
Readme and roadmap

### ISSUE THREAD

**Issue by davidandl** [agentm/project-m36#14]
Just discovered your project -- I don't read much Haskell. Congratulations! Thought you might like some additions for your readme/roadmap.

There are about 5 other projects aiming to do much the same thing, including mine: andl.org. You might mention them: I can provide a list.

CJ Date and the 'Tarpit' paper are excellent resources. You might also mention EF Codd, Darwen, 'The Third Manifesto, 'The Helsinki Declaration', 'Hall-Hitchcock-Todd' and the 'Alice' book.

[I have some questions too, if you could spare the time.]

**Comment by AndrewWarden** [comment]
Thanks, davidandl.  May I refer the owner of this project to my web site www.thethirdmanifesto.com for further information.  In particular, the language Tutorial D was jointly devised by Hugh Darwen and Chris Date (and there's a blank between Tutorial and D).  Also the paper The Third Manifesto was coauthored by those two, as have been all the books based on that paper.

The owner of M36 might also be interested in having an entry for the project on the Projects page at www.thethirdmanifesto.com, in which case I can be contacted via that web site.

**Comment by agentm** [comment]
Sure, @AndrewWarden- the more, the merrier. This project was inspired by several of Chris Date's books.
