### ISSUE TITLE
Add Atomable instance for NonEmpty

### ISSUE THREAD

**Issue by 3noch** [agentm/project-m36#142]
Perhaps `NonEmpty` would need to be added to the supported data types as well? Or perhaps it's a list with a constraint that it always has at least one element?

**Comment by agentm** [comment]
Won't this require a new type in the server to enforce the non-emptiness? In other words, converting a NonEmpty list to a list would be a lossy operation, right?

**Comment by 3noch** [comment]
Yes it would.

**Comment by agentm** [comment]
@YuMingLiao, this would be a relatively simple task, with plenty of example code already available.

**Comment by ilyakooo0** [comment]
Shouldn't this be resolved? 
https://github.com/agentm/project-m36/blob/a3402fc9a8e1ddbd23f24881d0efdf9384ac2581/src/lib/ProjectM36/Atomable.hs#L160-L166

**Comment by agentm** [comment]
Indeed. Fixed in d8ab441c701c18d7d7eb53551646fa9fba5df1f4.
