### ISSUE TITLE
user confused by notification returning previous value

### ISSUE THREAD

**Issue by agentm** [agentm/project-m36#157]
Notifications currently return the previous value of the relvar with the rationale that it might be otherwise hard to get those original values while getting the latest values is far easier. 

We should add a configuration flag to the notification creation to return the previous value, the newly-committed value, or both.

@diogob hit this issue during his Toronto presentation.

**Comment by agentm** [comment]
A alternative design may be to take two expressions to execute: one in the old context, and one in the new context. That seems more obvious than offering options.

**Comment by 3noch** [comment]
Could you pass both to the same expression?

**Comment by agentm** [comment]
Sure, but the rationale for not doing that is that the user may want to issue a completely separate query. Imagine, for example, that an application needs to mail a form to a customer when that customer's address changes. The notification callback could be arbitrarily complex in order to gather all the new data for the form, but only need the old address for customer confirmation.

In most cases, though, I imagine users will want either a new or old context query, so one query will be a no-op.

**Comment by 3noch** [comment]
I'm imagining a case where you want to *compare* the two values (do a diff, essentially). Would that be easy if the values were sent to two different expressions? If they were sent to the same expression, could the user split them and issue two different expressions himself if desired?

**Comment by agentm** [comment]
We do support trans-graph relational expressions which allow queries to span transactions, but then the argument to the notification would have to be a scripted function of type `TransactionId -> TransactionId -> TransactionGraph -> Relation` which seems rather loose and rather complicated for users to implement.

We don't currently have any DDL or DML diff tools in place. From your description, I would imagine you would like to see some ADT describing the changes between the contexts. I think that's a fair request, but we don't have anything to represent that right now. Would you want to the see the `DatabaseContextExpr`s which changed the relexpr in question? Do you envision something else?

Check out #159 for a proposed implementation and here are the [new docs](https://github.com/agentm/project-m36/blob/157_old_new_notif_context/docs/using_notifications.markdown). As you can see, the changes are quite straightforward and basically in-line with what was already in place.

What do you think?

**Comment by 3noch** [comment]
As far as I can tell this looks good! I suppose, with a little wrestling a client could get the before/after and run a comparison.

**Comment by agentm** [comment]
Yea, unfortunately, any diff would need to be manual for now. The user can load the notification relations back into Project:M36 and perform any operation he wishes, though. For example, he could save the results for audting purposes or for a work queueing system.
