### ISSUE TITLE
add Tupleable typeclass to use different attribute/field names

### ISSUE THREAD

**Issue by agentm** [agentm/project-m36#163]
Currently, the `Tupleable` interface offers no control over the naming scheme when mapping record field names to attribute names- they are simply mapped one-to-one. @3noch suggested that `Tupleable` could include some bi-directional name overriding mechanism.

**Comment by 3noch** [comment]
Lens has one of the best systems for deriving names. It uses TH but I'm sure you could achieve similar with Generics.

**Comment by YuMingLiao** [comment]
hi, I would like to understand more about this feature.
We already have `rename`.
What's the scenario of this? When we need two different names on both side?

**Comment by agentm** [comment]
We have a sort of ORM-like typeclass called `Tupleable` which marshals Haskell record types to Project:M36 tuples deriveable using `GHC.Generics`. Currently, the mapping uses the record names directly from Haskell. If a user wanted to map a Haskell record to a tuple with different names, he would have to reimplement the entire typeclass.

This feature request is to allow for generic derivation while allowing the user to override certain record attribute names in a bi-directional fashion.

I am not certain on the best way to accomplish this.

**Comment by YuMingLiao** [comment]
I see. I can't feel what's the overriding occasion right now. I'll try something else first. Still, thanks for response.

**Comment by ilyakooo0** [comment]
As an idea: this could probably be done with a type family which maps data types to type-level lists of strings with a default generic implementation.

**Comment by samb96** [comment]
You could use a solution similar to [the one used by Dhall](https://hackage.haskell.org/package/dhall-1.33.1/docs/Dhall-Deriving.html). Its generic implementation takes an argument with the relevant options. To support deriving it supplies [a newtype wrapper](https://hackage.haskell.org/package/dhall-1.33.1/docs/Dhall-Deriving.html#t:Codec) with a phantom type representing the options.

If you like this solution I'd be willing to implement it.

**Comment by agentm** [comment]
@samb96, thanks for the links! I had not considered that option and it looks really promising. By all means, I would be happy to accept such a merge request, especially since it seems like it should not alter the existing API.

**Comment by samb96** [comment]
@agentm I'm almost done, but after testing I realized it will require one change to the API. The type for `toAttributes` will no longer be able to have a polymorphic `proxy` type variable because it prevents GeneralizedNewtypeDeriving/DerivingVia. The new type will have to be `Proxy a -> Attributes`.

**Comment by agentm** [comment]
Wow, that was fast! I look forward to the pull request. That API change seems reasonable.
