### ISSUE TITLE
Update using Client.Simple causes key error

### ISSUE THREAD

**Issue by ruhatch** [agentm/project-m36#176]
I tried to run an `Update` `DatabaseContextExpr` using `withTransaction` from `Client.Simple`. The expression executed fine, but I got a `Left (RelError (InclusionDependencyCheckError "relvar_key"))` at the end of the transaction. I hunted this down to `autoMergeToHead`.

I tried to change the `MergeStrategy` by using `withTransactionUsing`. I use `headName` to get the head of the disconnected transaction as `headName'`. `UnionPreferMergeStrategy headName'` also gave a key error, and `SelectedBranchMergeStrategy headName'` didn't propogate the updates.

**Comment by agentm** [comment]
I am able to easily reproduce this based on the description. Thanks!

**Comment by agentm** [comment]
I have fixed this issue by implementing fast-forward commits, when possible using `autoMergeToHead`. This should eliminate the frustration surrounding merge commits in simple cases. 

However, the greater, underlying issue surrounds the over-simplicity of the current merge strategies. Once we store better transaction diff information, smarter merge strategies will be able to use them. I will open a separate ticket for such an implementation.
