### ISSUE TITLE
Single relation DDL, DML

### ISSUE THREAD

**Issue by kanishka-azimi** [agentm/project-m36#189]
I work a moderate size web application where most of its tables are modeled and stored in Postgres.

We have one table that needs to be customized per user. Ideally, we would use an off the shelf Haskell library to implement all DDL and DML operations for a single table in memory, and then persist the relation definition and relation contents to postgres whenever they changed.

Would you recommend forking this library to accomplish that? Are there other libraries in this space that you would recommend?

**Comment by agentm** [comment]
The use-case you describe is certainly possible and we have at least one user doing something similar, however, the implementor will need to be keenly aware of the feature differences between postgresql and Project:M36. For example, postgresql does not support algebraic data types, nested relations, or a transaction graph and Project:M36 does not support SQL or indexing. The implementor would also need to create the Project:M36<->postgresql mapping which, depending on your scenario, could be non-trivial.

You might also evaluate SQLite and postgresql temporary tables.

In any case, let us know how we can help to inform your design decision.

**Comment by kanishka-azimi** [comment]
This library seems like the only option for having a definition of the relation in memory, where there can be DDL operations like adding a column, while still being able to hijack the DML logic to write to one fat table with all columns nullable. I don't need anything fancier like nested relations.

I could have used something like sqlite, if there was a Haskell implementation of the sqlite engine (not just bindings to it's query interface).

It will be sometime until my use case matures enough to actually use m36 instead of a simple imitation fork, but if you take interest in this use case, I would want only the following:
- data types for expressing definition of a relation, and it's contents
- operations for modifying the relation definition, which operating on an in memory dictionary
- interface for expressing queries, DML, but not tied to any implementation

Then I would take this skeleton and implement as desired.

**Comment by agentm** [comment]
In that case, I think Project:M36 would suit your use-case just fine. 

* The [`Tupleable`](https://github.com/agentm/project-m36/blob/master/docs/tupleable.markdown) interface will allow you to marshal Haskell ADTs to tuples and back.
* Project:M36 certainly supports transaction-safe DML.
* Both DML and DDL interfaces (also Haskell ADTs) could be sent to a secondary, SQL-based engine, though not all the features would make sense.

Be aware that Project:M36 [does not support NULL](https://github.com/agentm/project-m36/blob/master/docs/on_null.markdown), however, `Maybe` as a value is supported and can approximate NULL but without three-valued logic.

**Comment by agentm** [comment]
Let me know if you have any more questions; I will close this ticket for now.

**Comment by kanishka-azimi** [comment]
Thanks for your help.
