### ISSUE TITLE
does tutorialD has utf-8 support?

### ISSUE THREAD

**Issue by YuMingLiao** [agentm/project-m36#195]
Hi, I just found this functional relational algebra database.  Math operators and functional pureness really helps me better understand database than sql syntax.  I can easily project what I want by group and sum() and ... etc...It feels like a great database choice. Great Work!

And this is not an issue, just a question.

After I type some traditional Chinese characters in a tutd file and import it, it says:
ERR: ImportError "scripts/ClassExamples.tutd: hGetContents: invalid argument (invalid byte sequence)"

and in tutorialD commandline, I insert some characters and it become:
│"\24278\20104\37528"│

Does it mean it does not support utf8 right now?

**Comment by agentm** [comment]
Hi @YuMingLiao, sorry about that. The intention was always to support UTF-8. I'll fix this right away.

**Comment by agentm** [comment]
@YuMingLiao, a [new branch](https://github.com/agentm/project-m36/tree/195_improved_utf8_support) contains the fix for terminal display of mutlibyte characters.

However, I was not able to reproduce the tutd file import failure. Here is my test file in UTF-8:

`
x:=relation{tuple{a "于"}}
`
which imports without errors.

Could you provide your test file which fails?

**Comment by YuMingLiao** [comment]
I am not sure if my computer setting is related or not.
for reference:
I am using babun in windows 10.
my locale tried en.UTF-8, zh_TW.UTF-8, and get the same output error.

TutorialD (master/main): :importtutd "scripts/ClassExamples.tutd"
ERR: ImportError "scripts/ClassExamples.tutd: hGetContents: invalid argument (invalid byte sequence)"

I attached my test file here. It only has one utf8 character in a tuple in `s` relation variable.
 


(github didn't support tutd, so I add .txt extension to upload this file..)
[ClassExamples.tutd.txt](https://github.com/agentm/project-m36/files/1892416/ClassExamples.tutd.txt)

**Comment by YuMingLiao** [comment]
I can't use stack or cabal to build new branch now. One is "Process exited with code: ExitFailure 1" and the other is "... trouble fulfilling ...". I am still trying to figuring out the setting. 
Sorry about the inconvenience for checking on my side.

And glad to know it works for terminal display now! Thank you for the instant help!

**Comment by agentm** [comment]
I see- the wcwidth module doesn't work on Windows, so I'll need to do some work on it. You should stick to master for now.

I am able to import your sample file on Linux using the `zh_TW.utf8` locale, so there must be going something wrong on Windows. I'll be able to take a closer look tomorrow. Sorry for the trouble- at least it works on Linux :-/

By the way, are you using MinGW bash or a different terminal?

**Comment by YuMingLiao** [comment]
No trouble at all. I am just glad I found a great, easy-to-understand database to learn. It is truly a great work!

I am using babun / cygwin. 

Since there is nothing wrong on Linux, I guess it's something wrong on the windows part. I'll report here if I found something. Pardon me for lacking experience. And thank you for taking time verifying this.

**Comment by agentm** [comment]
@YuMingLiao, the 195_improve_utf8_support branch is now compiling on Windows with new UTF-8 tests passing. Please try this branch and let me know if it works for you.

The change I made was to unconditionally output UTF-8 on data export and import. This may make some Windows use-cases more difficult but will, in general, allow any tutd file to be shared without worrying about specific encodings.

I don't have plans to implement support for alternative encoding at this time, though I don't exclude the possibility that such a feature could be useful in the future.

**Comment by YuMingLiao** [comment]
I stack built the 195_improve_utf8_support branch. it works when importing a tutd with utf8, and it also works when inserting a tuple with utf8 in command-line mode. I can see utf8 in both situations now.  Confirmed. That's wonderful! Thanks a lot!

**Comment by agentm** [comment]
The branch has been merged to master.
