### ISSUE TITLE
fix declaring Interval type

### ISSUE THREAD

**Issue by agentm** [agentm/project-m36#205]
`Interval x` is currently consumed in the primitive type parser as `Int`. I should probably just unify the type parser and perform post-processing to detect primitive data types.

**Comment by agentm** [comment]
@diogob, no, you're not doing anything wrong. The data type is not declared and parsed properly. However, if you create a relation with one tuple using `fromGregorian`, then the DateTime type can be used. I'll fix this as part of the type parsing overhaul.

**Comment by diogob** [comment]
Thanks for the quick response 😄
