### ISSUE TITLE
RelationTypeMismatchError in IsomorphicSchema example

### ISSUE THREAD

**Issue by YuMingLiao** [agentm/project-m36#216]
```
TutorialD (master/main): x1:=relation{tuple{y 3}, tuple{y 4}}
TutorialD (master/main): x2:=relation{tuple{y 5}, tuple{y 6}}
TutorialD (master/main): :addschema spam (isorestrict "x" "x1" "x2" ^lt(@y,5), isopassthrough "true", isopassthrough "false")
ERR: MultipleErrors [RelationTypeMismatchError [] [],RelationTypeMismatchError [] []]
TutorialD (master/main): :showexpr x1
┌──────────┐
│y::Integer│
├──────────┤
│3         │
│4         │
└──────────┘
TutorialD (master/main): :showexpr x2
┌──────────┐
│y::Integer│
├──────────┤
│6         │
│5         │
└──────────┘
```
Like in #111, I feel there is a need to log the evaluation process, especially when the process is getting bigger.

**Comment by agentm** [comment]
Yea, the error handling could be greatly improved with more context.

I'll take a look at what I broke and why the automated tests didn't catch this...

**Comment by agentm** [comment]
Wow, thanks for catching this- I thought the bug would be deep in the isomorphic schema code, but it turned out to be very basic- `typeForRelationalExpr` didn't function properly for `ExistingRelation`. I'm not sure how this code worked before! 

This is now fixed with test coverage.

**Comment by YuMingLiao** [comment]
Thanks for fixing it! Good to have you!
