### ISSUE TITLE
Docs: Persistent Library Driver

### ISSUE THREAD

**Issue by jmatsushita** [agentm/project-m36#224]
Hi, the [docs mention](https://github.com/agentm/project-m36/blame/master/docs/15_minute_tutorial.markdown#L299)  a persistent library driver document which isn't there.

**Comment by agentm** [comment]
As you discovered, the persistent driver is now separate from this project. I sent @YuMingLiao 's project a pull request with some fixes and and an update to support the new dataframes feature.
