### ISSUE TITLE
can't use project-m36 as a package.

### ISSUE THREAD

**Issue by YuMingLiao** [agentm/project-m36#233]
I can stack build project-m36 as a main project.
But I can't use it as a dependency.
It will require deferred-folds-0.9.7.1.
I tried 0.9.7.1 and 0.9.10.0, but they all failed at some code about `PrimArray`.

Has anyone successfully installed project-m36 as a dependency?

**Comment by YuMingLiao** [comment]
Okay, after I add primitive-0.6.4.0 to extra-deps, project-m36-0.5.1 and 6.0  both successfully compiled. So it's because lts-12.11 only has primitive-0.6.3.0.

**Comment by agentm** [comment]
Yes, I've hit the same problems. They are all related to stm-containers which has a lot of sub-package churn, but the packages are all owned by the same author and he is typically responsive.
