### ISSUE TITLE
can't get right ConstructedAtomType from Atomable typeclass.

### ISSUE THREAD

**Issue by YuMingLiao** [agentm/project-m36#236]
```
λ> data A = A { a :: Bool, b :: Int } deriving (Eq, Show, Ord, Generic, Binary, NFData, Atomable)
λ> toAtomType (undefined :: Proxy A)
ConstructedAtomType "A" (fromList [])
```

```
λ> toAtom (A True 1)
ConstructedAtom "A" (ConstructedAtomType "A" (fromList [])) [BoolAtom True,IntAtom 1]
λ> fromAtom $ toAtom (A True 1)

<interactive>:33:1: warning: [-Wtype-defaults]
    • Defaulting the following constraints to type ‘Integer’
        (Show a0) arising from a use of ‘print’ at <interactive>:33:1-28
        (Atomable a0) arising from a use of ‘it’ at <interactive>:33:1-28
    • In a stmt of an interactive GHCi command: print it
*** Exception: improper fromAtomConstructedAtom "A" (ConstructedAtomType "A" (fromList [])) [BoolAtom True,IntAtom 1]
CallStack (from HasCallStack):
  error, called at /root/project-m36/src/lib/ProjectM36/Atomable.hs:64:16 in main:ProjectM36.Atomable
λ>
```
```
λ> toAddTypeExpr (undefined :: Proxy A)
AddTypeConstructor (ADTypeConstructorDef "A" []) [DataConstructorDef "A" [DataConstructorDefTypeConstructorArg (PrimitiveTypeConstructor "Bool" BoolAtomType),DataConstructorDefTypeConstructorArg (PrimitiveTypeConstructor "Int" IntAtomType)]] 
```

**Comment by YuMingLiao** [comment]
Oops. Sorry for the noise.
fromList [] means no type variable in the type constructor. And that's nothing wrong.

But I still got an error in my project with project-m36-typed.

2019-05-06 11:30:32.029902: [info] attempting rollback after encountering errorDbQRelError (TypeConstructorAtomTypeMismatch "User" (C
onstructedAtomType "User" (fromList [])))

I'll report it if it's related to project-m36. Closed.

**Comment by agentm** [comment]
Sure. Also let me know if what ways the error-reporting could be improved. I hit errors myself which are not always clear- I've been thinking of adding more context to the error reporting, but I don't have a plan for how to make it consistent.

**Comment by YuMingLiao** [comment]
Sure.

It turns out that I just forgot to toAddTypeExpr  (undefined :: User). haha, free jokes.
I just figure that out when I trace where TypeConstructorAtomTypeMismatch is located.
I was trying to auto-generate those new datatypes form a user-defined Schema in project-m36-typed.
I was thinking which `relation type` can express `DbRecord User` well. "Should I store User as ConstructedAtomType or a plain relation with extended attributes as additional record information?"


So, when TypeConstructorAtomTypeMismatch, I wish to see something like "
ConstructedAtomType "User" (fromList []) is used in attribute (dbRecordRecord :: User) in relvar `Users`, but not listed in database datatypes: Int, Day, ...Maybe a..... Maybe you need to create it first before use it."

If let me make a big wish, I hope there are:
1. a consistent language/expression that can be used both in haskell and tutd.
(so that it can be divide and conquer when checking every part of an expression)
2. Every action/operator/expression has a clear road map/ implementation steps.
3. If an error occurs, it will shows what the context is now, the steps needed, the steps finished, and the step that went wrong, and (maybe) how-to-fix recommendation

If a simple expression can have this overall check, then it will boost confidence to debug a more complicate expression like a big schema or nested expression.

 
--
`exception call traces` in [control-monad-exception](http://hackage.haskell.org/package/control-monad-exception) looks nice, though I haven't used it. Worth taking a look.

**Comment by YuMingLiao** [comment]
hi @agentm 

I saw this today. They have implemented "Relation Types" in Haskell for a relational algebra C++ library.
[2 03 Types for a Relational Algebra Library - YouTube](https://www.youtube.com/watch?v=FAeSevC0QbY)
I guess it's worth mentioning here.

**Comment by agentm** [comment]
Thanks. I think you've summarized my thoughts on reasonable error reporting as well.
