### ISSUE TITLE
Remove GHC 8.0

### ISSUE THREAD

**Issue by ilyakooo0** [agentm/project-m36#248]
We should probably remove GHC 8.0 since it's not included in CI and doesn't even build.

**Comment by agentm** [comment]
Thanks- will do. Also, if we don't replace distributed-process soon, we can't move beyond GHC 8.4. Any suggestions for drop-in, Haskell-specific RPC?

**Comment by ilyakooo0** [comment]
Their latest GitHub commits actually compile fine under GHC 8.6.

You might want to have a look at #249

**Comment by agentm** [comment]
Fixed in c4bc709f3f7ac2e6ae417e1faa3fa1e262c58f21.
