### ISSUE TITLE
compile and test against GHC 8

### ISSUE THREAD

**Issue by agentm** [agentm/project-m36#25]
At least one of the distributed libraries will need its cabal bounds widened.

**Comment by agentm** [comment]
The only modules holding us back now are

* distributed-process-extras
* distributed-process-client-server

which include upper bounds blocking us from compiling under GHC 8. I will make pull requests to those repos shortly.

Compiling with GHC 8 has identified some minor fixes needed due to newly-introduced warnings. They will be resolved as part of this issue.

**Comment by agentm** [comment]
I am able to compile the ```tutd``` binary with GHC 8 on the 25_ghc_8 branch using ```cabal configure --allow-newer=binary,time``` which is not ideal but a useful workaround for now.

**Comment by agentm** [comment]
Thanks to help from ezyang, we are now able to build with GHC 7.10 or GHC 8. Merged in 2097579327617cbd3d6a9895185f925ec3110b14.

**Comment by agentm** [comment]
Project:M36 can now be built with ```cabal new-build``` and GHC 8. The requisite ```cabal.project``` file allows us to include multiple cabal packages in a single repo and specify "allow-newer" for the few distributed-process-* modules which haven't increased their time and binary upper bounds.

**Comment by diogob** [comment]
@agentm I've just sent a PR to https://github.com/haskell-distributed/distributed-process-extras/pull/17 and https://github.com/haskell-distributed/distributed-process-async/pull/10 to make then compatible with lts-7.14 under ghc 8.

**Comment by agentm** [comment]
Thanks! Oddly, I sent in a [pull request for the same issue](https://github.com/haskell-distributed/distributed-process-extras/pull/15/files) but I forgot to patch the time package. Oops!

**Comment by 3noch** [comment]
Those pull requests will not do the trick. The version bounds need to be expanded on the current released version of `distributed-process-extras`. The current `master` branch will not build with `distributed-process-client-server`.

**Comment by diogob** [comment]
@3noch I'm building off master branches directly using stack (bypassing hackage for now just to get the ball rolling). But there are necessary code changes indeed, I haven't had time to dig deeper yet.

**Comment by 3noch** [comment]
As long as you jailbreak/allow-newer a few packages everything seems to work just fine using the versions on Hackage.

**Comment by agentm** [comment]
By the way, I added a cabal.project file, so, if you have cabal 1.24, ```cabal new-build``` should just work. The project file includes the necessary evil allow-newer flags. I am using ```new-build``` for GHC 8 exclusively.

**Comment by 3noch** [comment]
@agentm Yah that does work because it's still using the versions on Hackage. I'm doing the same thing in my Nix derivation: https://github.com/3noch/project-m36/blob/nix-build/common.nix
