### ISSUE TITLE
No documentation on Hackage

### ISSUE THREAD

**Issue by kozross** [agentm/project-m36#250]
There doesn't appear to be any documentation on Hackage for this, at least for the last two releases.

**Comment by agentm** [comment]
The [build log](http://hackage.haskell.org/package/project-m36-0.7/reports/2) explains that `network-transport-tcp` sets an upper bound on `containers` which is not compatible with GHC 8.6. Hackage is still using `v1-install` to build documentation so cabal is not picking up the `cabal.project` file which relaxes that module constraint.

Our CI doesn't build with `v1-*`, so it's no surprise that this slipped through. I'm not quite sure what short-term action to take, but the long-term plan is to replace `distributed-process` with an RPC module that is maintained.

I can confirm that `v2-haddock` completes successfully, so it is possible to build docs locally, at least.

Any ideas for a short term fix?

**Comment by kozross** [comment]
You can upload the documentation yourself, with ``cabal upload -d``, after you build it locally.

**Comment by agentm** [comment]
Thanks! The documentation for 0.7 is [now uploaded](https://hackage.haskell.org/package/project-m36-0.7).

For future reference, I had to run:

```
cabal new-haddock --haddock-for-hackage
cabal upload -d ./dist-newstyle/project-m36-0.7-docs.tar.gz  --publish
```
The docs appear to be in good shape now. Let me know if any links are broken.

**Comment by ProofOfKeags** [comment]
Just stumbled on this. Can anyone upload docs to hackage??

**Comment by agentm** [comment]
Shoot- sorry about that. They're uploaded now and I've put the haddocks upload on my release checklist.
