### ISSUE TITLE
DecodeOptions undocumented

### ISSUE THREAD

**Issue by kozross** [agentm/project-m36#251]
Going by [``ProjectM36.Relation.Parse.CSV``][1], there is a publically-visible value ``csvDecodeOptions`` of type ``DecodeOptions``. However, ``DecodeOptions`` doesn't link to anything, and nothing in the module appears make use of a ``DecodeOptions`` argument.

[1]: http://hackage.haskell.org/package/project-m36-0.7/docs/ProjectM36-Relation-Parse-CSV.html

**Comment by agentm** [comment]
Sorry, I'm not sure why the link is missing.

`DecodeOptions` is part of [cassava](https://hackage.haskell.org/package/cassava-0.5.2.0/docs/Data-Csv.html#t:DecodeOptions) and it's used in `csvAsRelation`, but really we could use `defaultDecodeOptions`.

**Comment by agentm** [comment]
Please re-open this ticket if you need further assistance.
