### ISSUE TITLE
The language cheat sheet

### ISSUE THREAD

**Issue by suhr** [agentm/project-m36#261]
It would be nice to have a list of all syntax, maybe with some examples.

**Comment by suhr** [comment]
Though https://github.com/agentm/project-m36/blob/master/docs/tutd_tutorial.markdown probably is such a cheat sheet.

**Comment by agentm** [comment]
Indeed, I can imagine a more condensed version of examples for each construct. I've actually been using C.J. Date's now outdated "Database In Depth" which has a final page with Tutorial D examples as a cheatsheet. I'll put something like that together to share.

**Comment by agentm** [comment]
Let me know what you think of the [new cheatsheet](https://github.com/agentm/project-m36/blob/master/docs/tutd_cheatsheet.markdown).

I didn't recall some of the syntax I myself had implemented, so the cheatsheet will be useful to me, as well.
