### ISSUE TITLE
EntryPoints: ambiguous reference Timeout

### ISSUE THREAD

**Issue by ysangkok** [agentm/project-m36#274]
```
    It could refer to
       either ‘Network.RPC.Curryer.Server.Timeout’,
              imported from ‘Network.RPC.Curryer.Server’ at src/lib/ProjectM36/Server/EntryPoints.hs:8:1-33
           or ‘System.Timeout.Timeout’,
              imported from ‘System.Timeout’ at src/lib/ProjectM36/Server/EntryPoints.hs:9:1-21
```

This is on commit e125b9a1d92e3c842c9f2335c2da8dac3b2a210a using GHC 8.10.3.

**Comment by agentm** [comment]
Ah, thanks for the report- this is due to recent code churn. I'll make sure that this works with GHC 8.10.

**Comment by ysangkok** [comment]
`import System.Timeout hiding (Timeout)` makes it compile for me.

**Comment by agentm** [comment]
Are you using stack or cabal directly?

**Comment by ysangkok** [comment]
Yes, using cabal-install 3.2.
