### ISSUE TITLE
Double cannot be parsed in a tutd file.

### ISSUE THREAD

**Issue by YuMingLiao** [agentm/project-m36#284]
In a file 178__Rank_Score.tutd:
`scores := relation{id Integer, score Double}{tuple{id 1, score 3.1 }};`

In tutd:
`TutorialD (master/main): :importtutd "178__Rank_Score.tutd" 
ERR: ParseError "ParseErrorBundle {bundleErrors = TrivialError 66 (Just (Tokens (' ' :| \"\"))) (fromList [Tokens (',' :| \"\"),Tokens ('E' :| \"\"),Tokens ('e' :| \"\"),Tokens ('}' :| \"\"),Label ('d' :| \"igit\")]) :| [], bundlePosState = PosState {pstateInput = \"scores := relation{id Integer, score Double}{tuple{id 1, score 3.1 }};\\n\\n\", pstateOffset = 0, pstateSourcePos = SourcePos {sourceName = \"import\", sourceLine = Pos 1, sourceColumn = Pos 1}, pstateTabWidth = Pos 8, pstateLinePrefix = \"\"}}"`

**Comment by agentm** [comment]
Oops- it's a really stupid bug. If you remove the space following the "3.1" above, then it will parse. I'll have this fixed shortly.
