### ISSUE TITLE
setup hosting for websocket server and test client

### ISSUE THREAD

**Issue by agentm** [agentm/project-m36#29]
A hosted version of the websocket client sample application along with the server could serve to introduce more users to Project:M36 without the need to download and compile Haskell or run a terminal application, thus lowering the barrier of access.
- [x] setup resource restrictions (memory, CPU) per connection- wipe the database when the limit is hit
- [x] disable file I/O
- [x] setup hosting (AWS free tier?)

**Comment by 3noch** [comment]
I'd be willing to set this up and host it for you. I'd use Google Compute Engine with NixOS and you could have access to the project and deployment privileges for your needs.

**Comment by 3noch** [comment]
Actually I'd be willing to use something other than GCE and NixOS if you wanted. That's just how I've been deploying things. AWS or DigitalOcean could work as well. As for NixOS, I'm very impressed with how powerful it is for defining servers, but I'd be up for something else too.

If you have a better option, then great. I'd just love to be a part of pushing this project forward.

**Comment by agentm** [comment]
Thanks @3noch. Any contribution here would be much appreciated. We currently don't have any automated deployment scheme in place, so any effort on that front would be big step up.

The only blocker I foresee here is some kind of statement timeout and memory limit to prevent DoS.

I am not familiar with NixOS but it sounds like a good fit from a functional programming perspective, so I defer here to your expertise and am willing to help however is needed.

**Comment by 3noch** [comment]
@agentm Great; can't wait to get something up and running. Please email me (see my profile) as I'll need some info like your PGP identity and SSH key to give you access to stuff.

**Comment by agentm** [comment]
After much help from @3noch, we were able to get https://try.project-m36.io up-and-running. I have added a reference to the main page.

I would still like to improve the look of the websocket client, but I will open separate tickets for that. The current interface is feature complete and comparable to the command line tutd client.

Many thanks to @3noch for configuring and generously hosting the site!

**Comment by YuMingLiao** [comment]
> I'd be willing to set this up and host it for you. I'd use Google Compute Engine with NixOS and you could have access to the project and deployment privileges for your needs.

Hi, @3noch , would you be willing to share the deployment script of GCE with nixos? I was planning to use nix-copy-closure to deploy project-m36 but stuck at something about ssh to nixos on GCE.

**Comment by 3noch** [comment]
@YuMingLiao It's *way* out of date but maybe you could get it working from here: https://github.com/3noch/project-m36.io

**Comment by YuMingLiao** [comment]
@3noch Thanks! That should be enough for me to follow.
