### ISSUE TITLE
Inconsistency between TutorialD and Client library

### ISSUE THREAD

**Issue by farzadbekran** [agentm/project-m36#299]
There is a minor inconsistency regarding relation variable names. Client library allows me to define relvars with names like `system.users` (i.e containing special characters), but if i go to tutd and try to run `:showexpr system.users` I get an unexpected character error.

**Comment by agentm** [comment]
It's true. The TutorialD language should allow names to be quoted. It should be a quick fix.

**Comment by agentm** [comment]
Resolved in b47ffdfb1a3800953854a68c3e58a509c9b49e96.
