### ISSUE TITLE
implement runtime-created Haskell atom functions

### ISSUE THREAD

**Issue by agentm** [agentm/project-m36#32]
We can use the GHC API to interpret Haskell functions at runtime. Obviously, we should retain the feature to compile in functions, but using Haskell with the Safe pragma would offer pure and safe (secure) runtime functions.

**Comment by 3noch** [comment]
Wow this would be amazing.

**Comment by agentm** [comment]
This is now in place. Some basic [documentation](https://github.com/agentm/project-m36/blob/master/docs/atomfunctions.markdown) is available.
