### ISSUE TITLE
add ":commitToBranch <branchname>" operator

### ISSUE THREAD

**Issue by agentm** [agentm/project-m36#33]
Creating and merging a branch currently takes three steps:
1. create the branch
2. make database context transformations
3. merge the branch back

It could make sense to merge two or all three of these into one step. Originally, I was thinking that a "commitToBranch" operator would allow creation of a new branch at commit-time, thus merging (1) and (2), but it may make sense to merge all three into an operator. This would simulate a serializable transaction sequence ala SQL without needing to constantly rebase against a moving transaction head.

Perhaps the operator encompassing all three steps could be ":commitAndMerge <headname>" whereby a dud branch is created from the current transaction point and merged to the head at commit-time.

**Comment by 3noch** [comment]
Would this also apply to detached transactions?

**Comment by agentm** [comment]
Ideally, this feature would handle a rebase against the current head atomically, so that no ```TransactionIsNotAHead``` error would be possible. Only errors related to DDL or DML changes since the query was issued would be generated. Rebasing is not always possible.

**Comment by agentm** [comment]
I called this feature "automerge". It is now available in master in 415eb12c23adcdd54502a3bd68bffbeb6cfe86f9.
