### ISSUE TITLE
arbitrary precision data type

### ISSUE THREAD

**Issue by boogerlad** [agentm/project-m36#333]
Is something like postgres `numeric` https://www.postgresql.org/docs/current/datatype-numeric.html#DATATYPE-NUMERIC-DECIMAL planned? I see you're using gmp for `integer`, so I'm hoping this is "easy"?

**Comment by agentm** [comment]
Sure- such a feature would probably pretty easy to add. Would you like to try to implement this? Perhaps [scientific](https://hackage.haskell.org/package/scientific-0.3.7.0) would be an appropriate backing module.

**Comment by boogerlad** [comment]
I would love to. Sadly, I don't know haskell, but if you can wait 6 months, I'll implement it. If not, feel free to implement.
