### ISSUE TITLE
AttributeAndTypeNameExpr vs NakedAttributeExpr

### ISSUE THREAD

**Issue by YuMingLiao** [agentm/project-m36#356]
In client side, If I `Define ... [AttributeAndTypeNameExpr ...]` with an non-existent datatype, I get `NoSuchTypeConstructorError`. I found this error is easier for me to understand.

If I `Define ...[NakedAttributeExpr ...]` with an non-existent datatype, I get `TypeConstructorAtomTypeMismatch`. 

What's their difference? (project-m36-typed uses NakedAttributeExpr to define.)

**Comment by agentm** [comment]
The difference in the errors is that, in some contexts when we have multiple NakedAtomExprs, we know what type is expected, so we can return an error explaining which type was expected. In the above context though, the comparison type doesn't exist. I'll improve the error.

**Comment by agentm** [comment]
I think that you are right. In the context of an unknown type constructor, the correct error is `NoSuchTypeConstructorError`.

**Comment by YuMingLiao** [comment]
Thanks for the clarification and fixing. Amazing project!
