### ISSUE TITLE
Natural Join should act like Cross Join on relations that don't share attributes

### ISSUE THREAD

**Issue by Valdsonjr** [agentm/project-m36#361]
The article for 'join' states that the result of a natural join between two relations R and S that don't have any attributes in common is supposed to be a cross join, but an empty relation is returned instead.

Expected behavior: example in the [RelaX - relational algebra calculator](https://dbis-uibk.github.io/relax/calc/local/uibk/local/0)
![image](https://github.com/agentm/project-m36/assets/6580116/886a6551-d1fe-4949-8a99-824f29bc5a21)

Actual behavior:
![image](https://github.com/agentm/project-m36/assets/6580116/f5ed3447-399a-4b1d-92ef-6175438f7373)

**Comment by agentm** [comment]
Oh, good find! I'll fix this right away.
