### ISSUE TITLE
How do I identify which command is the WebSocket message replying to?

### ISSUE THREAD

**Issue by ratsclub** [agentm/project-m36#367]
I'm trying to write a Deno WebSocket client for M36 but I don't understand how to identify which message is which.

Consider the scenario where you have multiple HTTP requests doing operations on the database, you would end up with multiple commands being sent from the same WebSocket connection. How can I tell the responses apart? Is there a way to send and receive a unique identifier or something else?

**Comment by agentm** [comment]
Hm, the Haskell API has a SessionId precisely for this use-case but it looks like this API component was not exposed to Websockets. That's clearly an oversight, so we'll need to add this capability to the Websocket API to make this work. 

The intention is to allow one Session for each parallel-capable request- Sessions are effectively bound to potential (uncommitted) transactions.

Would that address your use-case?

**Comment by ratsclub** [comment]
I think that this is exactly what we are looking after!

**Comment by agentm** [comment]
We've overhauled the websocket API to use tagged JSON objects over the wire. Check out the [WebSocket TutorialD Client](https://github.com/agentm/project-m36/blob/master/src/bin/ProjectM36/Server/WebSocket/websocket-client.html) for an example usage.

This patch enabled `createSessionAtHead` support as well per request request UUIDs which are roundtripped from the client. Note that request UUIDs are not validated by the server- the client is presumed to reuse request UUIDs.
