### ISSUE TITLE
reduce compilation time by library-izing Project:M36 better

### ISSUE THREAD

**Issue by agentm** [agentm/project-m36#38]
The current cabal setup recompiles the Project:M36 library for every binary because an older version of cabal didn't support linking against a library in the same project. Now that it does, we should library-ize the shared modules to reduce compile times.

**Comment by agentm** [comment]
This is implemented in the "32_haskell_script" branch and has reduced compile times to 6 minutes for a full build compared to the 20 minutes previously. This could be further cut down by library-izing the TutorialD shared modules but cabal allows only one library per package, so something would have to be broken out into another cabal pacakge. That doesn't sound so appealing right now because that would make it more difficult for others to build.

**Comment by 3noch** [comment]
Unless you use stack! ;)

**Comment by diogob** [comment]
Yes, as @3noch pointed out we could split into several cabal packages and compile everything in one go using stack. I believe it's not hard to setup, I'd be willing to give it a try but I won't have any free time during the next 2 weeks.

**Comment by agentm** [comment]
Thanks for the feedback. The six minute build time is for a full, optimized, non-incremental build which is quite reasonable for now. I have been using [ghcid](https://github.com/ndmitchell/ghcid) to make sure I don't run the full build unnecessarily.

The biggest time reduction for me is actually in compiling tests since the most compile-time-intensive modules are now shared across all tests.

I certainly wouldn't reject any build-time-reducing patches, though!

**Comment by rvion** [comment]
In case it fit your workflow: those ghc options in `stack install --fast --file-watch --ghc-options="-j +RTS -A128m -n2m -RTS -dynamic"`  will improve the compile time when developping if you want to also produce usable executables.

**Comment by agentm** [comment]
Thanks for the tips, gentlemen.

The library target is now installed and used by all binaries. I will open secondary tickets to address further possible cabal improvements.
