### ISSUE TITLE
Add IPv6 support to websocket server

### ISSUE THREAD

**Issue by agentm** [agentm/project-m36#70]
While the project-m36-server does support IPv6 addresses, @3noch discovered that the project-m36-websocket-server does not.

```
project-m36-websocket-server: user error (inet_addr: Malformed address: ::1)
```

This appears to be a bug in the websocket library.

**Comment by 3noch** [comment]
Haha...more appropriately nginx forced us to discover this by deciding to resolve localhost to ::1.

**Comment by agentm** [comment]
I opened a [pull request](https://github.com/jaspervdj/websockets/pull/131) to get this fixed in the websockets library.

**Comment by agentm** [comment]
The only thing we can do here is wait until the next release of websockets to include IPv6, so I will close this ticket.
