### ISSUE TITLE
websocket server file handle leak

### ISSUE THREAD

**Issue by agentm** [agentm/project-m36#72]
After disconnecting from the websocket server, the connection remains open and holding a file handle. Soon enough, we run out of handles :cry: .

**Comment by agentm** [comment]
By running the project-m36-server independently and reconnecting several times to it, I found that the number of file handles is stable, so the bug must indeed be in the websocket code.

**Comment by agentm** [comment]
It took me some hours of testing and refactoring, but I was able to discover with help from [Tim Watson](https://github.com/haskell-distributed/distributed-process-client-server/issues/7) that the transport is not closed by the process nodes.

@3noch, we should no longer be leaking file handles. However, each new client uses 3 file handles and the current maximum on try.project-m36.io is 1024, so that allows the one process to service (1024 - 21 overhead)/3 = 331 simultaneous users which I think is sufficient for now.

**Comment by 3noch** [comment]
This is great news. I'll try to update the server ASAP.
