### ISSUE TITLE
create automated builders

### ISSUE THREAD

**Issue by agentm** [agentm/project-m36#76]
We are starting to see platform-specific compilation and run-time issues. We should create some automated builders, perhaps with [Bake](https://hackage.haskell.org/package/bake). To start, we should have:

* Linux (Ubuntu 16.04 LTS)
  * stack lts 6.27 (GHC 7.10.3) build+test
  * stack lts lts 7.18 (GHC 8.0.1) build+test
  * cabal with GHC 7.10.3 build+test
  * cabal with GHC 8.0.1/2 build+test
  * cabal new-build with GHC 8.0.2 build (no tests due to missing command)
* MacOS 10.7 
  * stack 6.27 (GHC 7.10.3) build+test
* Windows 8
  * stack 6.27 (GHC 7.10.3)
  * stack 7.18 (GHC 8.0.1)

Currently, I am doing these builds manually as time permits but that obviously adds unnecessary risk. These builders could also be used to create binary releases.

**Comment by 3noch** [comment]
I'd also like to see Project:M36 get added to Stackage which would also add it to Nixpkgs. Nixpkgs packages are distributed from pre-built cache and could be a reasonable way to get binaries for both MacOS and Linux.

**Comment by 3noch** [comment]
https://www.appveyor.com/ does Windows builds and is free for OSS.

**Comment by 3noch** [comment]
Of course TravisCI is an option too.

**Comment by agentm** [comment]
@3noch was gracious enough to create travis.yml integration.

What remains here are macOS and Windows support. We should probably set up appveyor integration.

**Comment by 3noch** [comment]
[Here is an example](https://github.com/tfausak/octane/blob/main/appveyor.yml) of an Appveyor configuration that uses `stack`. It may be possible to have `stack` install `cabal` or just install `cabal` directly.

**Comment by agentm** [comment]
We are building on macOS and Linux via TravisCI and Windows via Appveyor- all via stack.
