### ISSUE TITLE
Change Parsec parser to use Text

### ISSUE THREAD

**Issue by agentm** [agentm/project-m36#8]
Data.Text is now used internally everywhere, so it doesn't make sense to continue to use the String parser variant and pepper everything with "T.pack".

**Comment by rvion** [comment]
how about [megaparsec](https://hackage.haskell.org/package/megaparsec) ? (it is slowly replacing Parsec)
[Text.Megaparsec](https://hackage.haskell.org/package/megaparsec-4.3.0/docs/Text-Megaparsec.html)

**Comment by nd2s** [comment]
+1 for megaparsec, made my life easier.

**Comment by agentm** [comment]
Thanks for the suggestions. We have migrated successfully to megaparsec without much code churn. The conversion was mostly mechanical.

As a result of switching to megaparsec, in-line comment and multi-line support is much improved.
