### ISSUE TITLE
Use Generic to marshal Haskell ADTs to database ADTs and back

### ISSUE THREAD

**Issue by agentm** [agentm/project-m36#81]
This shouldn't be particularly controversial. It would be handy to pass ADTs back and forth to Haskell-land without the boilerplate.

**Comment by agentm** [comment]
I am looking into implementing this ticket with generics. Basically, I want to convert a type constructor:

```
data TestT a b = TestC a b deriving (Generic)
```
to:
```
ConstructedAtomType "TestT" ["a", "b"]
```
which Project:M36 supports. The issue is that extracting these type constructor variables seems impossible to do from GHC.Generics- there is no type constructor metadata for this. Is getting type constructor variables possible without resorting to Template Haskell?

**Comment by 3noch** [comment]
Are you specifically referring to the *names* of the constructor arguments (i.e. `a` and `b`)? Out of curiosity, why would you need that?

**Comment by agentm** [comment]
I wish to generate the equivalently-named type in the database. ```TestC``` would then become the name of the database type based on the Haskell type which can be loaded at runtime.

**Comment by 3noch** [comment]
Since `a` and `b` are nothing more than positional arguments, then wouldn't it suffice to just know how many positional arguments the type has (i.e. arity) and set up just as many positional arguments on the database side? Their name seems quite inconsequential since you can't even refer to those names in Haskell except in the declaration.

**Comment by agentm** [comment]
That's somewhat true. It would be nice to match the names the user used, but I'm willing to settle for less. Is it possible to get the arity of a type constructor? Any reference or example would help a lot.

**Comment by agentm** [comment]
Oops- I didn't mean to close this.

**Comment by 3noch** [comment]
Though I've never used it, `generics-sop` has a nice API over Generics. The `NP` type represents an n-ary product and gives you info about arity, etc. https://hackage.haskell.org/package/generics-sop-0.2.4.0/docs/Generics-SOP.html#t:NP

**Comment by 3noch** [comment]
Here are some examples of usage: https://hackage.haskell.org/package/basic-sop

**Comment by 3noch** [comment]
This just popped up on my feed. Looks interesting and possibly useful in this scenario: https://github.com/tittoassini/model

**Comment by agentm** [comment]
Thanks, @3noch. I was able to swipe the Generics design from the model package. Here is a preview of how the [out_of_the_tarpit.hs example has changed](https://github.com/agentm/project-m36/compare/81_adt_marshal?expand=1#diff-90e1fa1e8fa60522eaab645e7397911c) with the new Generics atom deriving in place.

**Comment by 3noch** [comment]
That's amazing! Excellent work!

**Comment by 3noch** [comment]
So far it looks great. Have you tried using the `TypeApplication` to clean up some of those `undefined`s?

**Comment by agentm** [comment]
This is now merged to master. The [documentation](https://github.com/agentm/project-m36/blob/master/docs/new_datatypes.markdown) has been updated and [an additional simple example](https://github.com/agentm/project-m36/blob/master/examples/hair.hs) has been added.

**Comment by agentm** [comment]
@3noch, it was not clear to me how TypeApplications could eliminate the undefined bottoms in the generics code. Aren't TypeApplications just annotations? If they would help to clean up the code, I would definitely like to learn more about it. The ```Atomable``` Generics code is probably the most abominable in the code base now, but it does actually work.
