### ISSUE TITLE
implement stored procedures

### ISSUE THREAD

**Issue by agentm** [agentm/project-m36#85]
Stored procedures have the signature and are stored by the server:

```
[Atom] -> DatabaseContextExpr
```

**Comment by 3noch** [comment]
Will these exist in the same way as other database entities (e.g. tables)? Can a stored procedure exist at one point in a transaction but not in another?

**Comment by agentm** [comment]
I haven't given much thought to all the consequences, but, yes, my initial plan is to add stored procedures to the database context (alongside value functions, relation variables, constraints, etc.) so they would be part of a transaction. At least, I don't see any limitations as to why this should not be the case.

Just off-hand, this approach seems like an improvement over postgresql, where versioning database functions is a hassle. At the very least, one would be able to pull out and run older versions of the function (which is useful for auditing, etc.)

> Can a stored procedure exist at one point in a transaction but not in another?

Assuming you mean "in one transaction but not in another in the transaction graph", I think the answer is "yes".

**Comment by 3noch** [comment]
That's the answer I was hoping for. I think traditional stored procedures are almost unbearable in most situations. Having them part of the transaction graph makes a lot of sense and definitely makes me feel much safer about using them.

**Comment by agentm** [comment]
Pushed to master in aeda5828f9d8aa340c5f028dba5a84d1eddbf3e7.
